version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    env_file: .env
    ports:
     - "${DB_PORT}:${DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
